# Generated by Django 4.1.4 on 2023-01-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_datecreated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='datecreated',
        ),
    ]
