# Generated by Django 4.1.2 on 2023-03-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
